### PR TITLE
Trl rlhf v1

### PR DESCRIPTION
**Pull request by Pchatain**
The PPO baseline to compare superhf with.

### CODE REVIEW

**Comment by mukobi** [comment]
image
lol could you remove the output files? or is there a reason to keep them?

**Comment by Pchatain** [comment]
I deleted the output files, hence the hundreds of file changes. e.g. batch_outputs/test_job.5881633.err is deleted, all of this leading to 
Screenshot 2023-05-07 at 10 34 00 PM

**Comment by mukobi** [comment]
Oh lol gotcha. Should I approve this, is it good?

**Comment by mukobi** [comment]
Lgtm 🤷🏾

**Pull request merged**
